// Phase 5B docs renderer: every number table in docs/economy/5b/<module>.md is GENERATED from the
// module's report at the current framework version, never hand-typed, so a version bump regenerates the
// docs mechanically.
//
// A module exports markdownTables() -> { [blockId]: markdown }. Its doc contains, for each block:
//   <!-- generated:<blockId> -->
//   ...(replaced on every render)...
//   <!-- /generated:<blockId> -->
// Each rendered block ends with a provenance line (framework version + shared digest).
// The final Phase 5B report (docs/economy/PHASE5B_REPORT.md) is rendered the same way from summary.js.
//
//   node scripts/economy/5b/render-docs.js            rewrite every doc's generated blocks
//   node scripts/economy/5b/render-docs.js --check    exit 1 if any doc is stale, a block is missing, or a
//                                                    doc marker has no table (run by check-shared.js)
const fs = require('node:fs');
const path = require('node:path');
const F = require('./framework');

const MODULES = ['rods', 'upgrades', 'bait', 'quests', 'streak', 'aquarium', 'founder', 'buffs', 'world', 'summary', 'delta'];
const DOCS = path.join(__dirname, '../../../docs/economy/5b');
// Docs that do not live at docs/economy/5b/<name>.md.
const DOC_PATHS = { summary: path.join(DOCS, '../PHASE5B_REPORT.md'), delta: path.join(DOCS, '../PHASE5B_DELTA.md') };
const docName = (name) => path.basename(DOC_PATHS[name] || `${name}.md`);
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function renderModule(name) {
	const mod = require(`./${name}`);
	const docPath = DOC_PATHS[name] || path.join(DOCS, `${name}.md`);
	const problems = [];
	if (typeof mod.markdownTables !== 'function') return { name, problems: [`${name}.js exports no markdownTables()`], changed: false };
	const tables = mod.markdownTables();
	const stamp = F.stamp();
	let doc = fs.readFileSync(docPath, 'utf8');
	const before = doc;
	for (const [id, md] of Object.entries(tables)) {
		const open = `<!-- generated:${id} -->`;
		const close = `<!-- /generated:${id} -->`;
		if (!doc.includes(open) || !doc.includes(close)) {
			problems.push(`${docName(name)} has no block ${id} (add ${open} ... ${close})`);
			continue;
		}
		const body = `${open}\n${md.trim()}\n\n<sub>Generated by \`node scripts/economy/5b/render-docs.js\` from \`${name}.js\` markdownTables() at framework ${stamp.frameworkVersion} (digest ${stamp.sharedDigest}).</sub>\n${close}`;
		doc = doc.replace(new RegExp(`${escapeRe(open)}[\\s\\S]*?${escapeRe(close)}`), () => body);
	}
	const docIds = [...doc.matchAll(/<!-- generated:([\w.-]+) -->/g)].map((m) => m[1]);
	for (const id of docIds) if (!(id in tables)) problems.push(`${docName(name)} has block ${id} but markdownTables() does not produce it`);
	return { name, docPath, doc, changed: doc !== before, problems };
}

function main() {
	const check = process.argv.includes('--check');
	const results = MODULES.map(renderModule);
	const problems = results.flatMap((r) => r.problems);
	const stale = results.filter((r) => r.changed).map((r) => r.name);
	if (check) {
		for (const s of stale) problems.push(`${docName(s)} is stale: run node scripts/economy/5b/render-docs.js`);
	}
	else {
		for (const r of results) if (r.changed) fs.writeFileSync(r.docPath, r.doc);
	}
	process.stdout.write(`${JSON.stringify({ ...F.stamp(), mode: check ? 'check' : 'write', rewritten: check ? [] : stale, problems }, null, 1)}\n`);
	if (problems.length) process.exit(1);
}

if (require.main === module) main();
module.exports = { MODULES, DOC_PATHS, docName, renderModule };
